<a href="https://colab.research.google.com/github/matheus-22cmd/project_ideas/blob/master/An%C3%A1lise_Agosto_2025_a_Jul_26_Ag%C3%AAncia_J%C3%BAnior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Instalando bibliotecas**

In [ ]:
!pip install fg-data-profiling pandas numpy matplotlib --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 28.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 25.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 93.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 43.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.8 MB/s eta 0:00:00

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
import data_profiling

In [ ]:
from data_profiling import profile_report
from google.colab import files

## 2. Subindo dados para análise

In [ ]:
uploaded = files.upload()

Saving Aug-01-2025_Jul-31-2026_1051292237892486.csv to Aug-01-2025_Jul-31-2026_1051292237892486.csv

In [ ]:
df = pd.read_csv('Aug-01-2025_Jul-31-2026_1051292237892486.csv')

# 3. Avaliando a qualidade dos dados

In [ ]:
#utilizando o profile report para verificar a qualidade dos dados coletados
from data_profiling import ProfileReport
profile = ProfileReport(df,title = "Profiling Report",explorative =True)
profile.to_file('report.html')
files.download('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/18 [00:00<?, ?it/s]
 28%|██▊       | 5/18 [00:00<00:00, 36.95it/s]
100%|██████████| 18/18 [00:00<00:00, 69.94it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df.shape

(93, 18)

In [ ]:
df.head()

,Identificação do post,Identificação da conta,Nome de usuário da conta,Nome da conta,Descrição,Duração (s),Horário de publicação,Link permanente,Tipo de post,Comentário de dados,Data,Visualizações,Alcance,Curtidas,Compartilhamentos,Seguimentos,Comentários,Salvamentos
0,18089425027840908,17841401896849967,rafaelfurtadorocha,Rafael Furtado | Comunicação,A grande diferença entre quem conquista e quem...,105,09/15/2025 14:39,https://www.instagram.com/reel/DOo0_96kfoq/,Reel do Instagram,Ocorreu um erro ao computar métricas.,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18071354273707051,17841434458249832,gestao.unifecaf,Gestão UniFECAF,Gestão não é cargo. É mentalidade. E mentalida...,0,07/31/2026 08:53,https://www.instagram.com/p/DbdobkrjuHS/,Carrossel do Instagram,NaN,Total,686.0,164.0,10.0,7.0,0.0,0.0,0.0
2,18609779563028754,17841434458249832,gestao.unifecaf,Gestão UniFECAF,Funcionário engajado não nasce motivado. \nEle...,23,07/29/2026 18:51,https://www.instagram.com/reel/DbZjNY2N5UQ/,Reel do Instagram,NaN,Total,433.0,322.0,10.0,1.0,0.0,0.0,0.0
3,18156534325491400,17841434458249832,gestao.unifecaf,Gestão UniFECAF,Essa frase é repetida em todo RH do Brasil e e...,0,07/28/2026 14:38,https://www.instagram.com/p/DbWhkJPOgS-/,Imagem do Instagram,NaN,Total,217.0,105.0,9.0,1.0,0.0,2.0,1.0
4,18106250942028357,17841434458249832,gestao.unifecaf,Gestão UniFECAF,Tem uma sensação que só brasileiro conhece. 💚\...,0,07/24/2026 20:49,https://www.instagram.com/p/DbM40WvjSyc/,Carrossel do Instagram,NaN,Total,990.0,402.0,76.0,9.0,1.0,12.0,1.0

In [ ]:
df.dtypes

Identificação do post         int64
Identificação da conta        int64
Nome de usuário da conta     object
Nome da conta                object
Descrição                    object
Duração (s)                   int64
Horário de publicação        object
Link permanente              object
Tipo de post                 object
Comentário de dados          object
Data                         object
Visualizações               float64
Alcance                     float64
Curtidas                    float64
Compartilhamentos           float64
Seguimentos                 float64
Comentários                 float64
Salvamentos                 float64
dtype: object

*Soma de valores perdidos*

In [ ]:
df.isnull().sum()

Identificação do post        0
Identificação da conta       0
Nome de usuário da conta     0
Nome da conta                0
Descrição                    0
Duração (s)                  0
Horário de publicação        0
Link permanente              0
Tipo de post                 0
Comentário de dados         92
Data                         0
Visualizações                1
Alcance                      1
Curtidas                     1
Compartilhamentos            1
Seguimentos                  1
Comentários                  1
Salvamentos                  1
dtype: int64

*Procurando valores perdidos*

In [ ]:
# Seção de comentários de dados está 98% vazia
missing = df.isnull().mean()*100
print(missing[missing >0].sort_values(ascending = False))

Comentário de dados    98.924731
Visualizações           1.075269
Alcance                 1.075269
Curtidas                1.075269
Compartilhamentos       1.075269
Seguimentos             1.075269
Comentários             1.075269
Salvamentos             1.075269
dtype: float64

In [ ]:
n_dupes = df.duplicated().sum()

In [ ]:
n_dupes

np.int64(0)